### ISSUE TITLE
Color pallet for the theme color not fully appearing

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/montana#1]
If we try to change the color for the theme color , the theme pallet will not be fully displayed : https://prnt.sc/uqtpar

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
