### ISSUE TITLE
Header color section , color pallet not fully displaying 

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/montana#3]
The color pallet for the following header color section elements is not fully displaying : 
Sticky Header BG Color : https://prnt.sc/uqu29y
Header menu color: https://prnt.sc/uqu39o
Header menu hover border color : https://prnt.sc/uqu4ao

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
