### ISSUE TITLE
Footer color pallet not fully appearing

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/montana#8]
The color pallet for the following footer options is not fully appearing :
Footer Text Color: https://prnt.sc/uquw4y
Footer Anchor Color : https://prnt.sc/uquwdu
Footer Anchor Hover Color: https://prnt.sc/uquwkx

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
